// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProyectoFinal_TiendaNet.Config;

#nullable disable

namespace ProyectoFinal_TiendaNet.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250630210218_Agregado de entidad Comprador")]
    partial class AgregadodeentidadComprador
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ProyectoFinal_TiendaNet.Rol.Model.Rol", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Rol");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Nombre = "Admin"
                        },
                        new
                        {
                            Id = 2,
                            Nombre = "Comprador"
                        },
                        new
                        {
                            Id = 3,
                            Nombre = "Vendedor"
                        });
                });

            modelBuilder.Entity("ProyectoFinal_TiendaNet.Usuario.Model.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contraseña")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("datetime2");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RolId")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RolId");

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Apellido = "Leiva",
                            Contraseña = "12345678",
                            Email = "gleiva@frsn.utn.edu.ar",
                            FechaRegistro = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Gregorio",
                            RolId = 1,
                            Username = "gleiva"
                        },
                        new
                        {
                            Id = 2,
                            Apellido = "Leiva",
                            Contraseña = "12345678",
                            Email = "gleiva@frsn.utn.edu.ar",
                            FechaRegistro = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Gregorio",
                            RolId = 3,
                            Username = "gregorio"
                        },
                        new
                        {
                            Id = 3,
                            Apellido = "Leiva",
                            Contraseña = "12345678",
                            Email = "gleiva@frsn.utn.edu.ar",
                            FechaRegistro = new DateTime(2025, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Nombre = "Gregorio",
                            RolId = 2,
                            Username = "goyo"
                        });
                });

            modelBuilder.Entity("ProyectoFinal_TiendaNet.Usuario.Model.Usuario", b =>
                {
                    b.HasOne("ProyectoFinal_TiendaNet.Rol.Model.Rol", "Rol")
                        .WithMany()
                        .HasForeignKey("RolId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");
                });
#pragma warning restore 612, 618
        }
    }
}
